name: CI/CD Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH agent
        # Using stable recommended syntax
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "echo 'SSH connection works!'"
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'ENDSSH'
            echo "Deploy started..."
            cd ~/College-Event-Management-System || exit
            git reset --hard
            git pull origin main
            docker build -t college-event-app .
            docker stop college-event-container || true
            docker rm college-event-container || true
            docker run -d -p 80:80 --name college-event-container college-event-app
            echo "Deploy finished!"
          ENDSSH
